Add support for concourse deployments
- mostly configuring different load balancers

Signed-off-by: Desmond Pompa Alarcon Rawls <captaingrover@gmail.com>

diff --git a/bbl-up/task b/bbl-up/task
--- a/bbl-up/task
+++ b/bbl-up/task
@@ -5,15 +5,24 @@ source cf-deployment-concourse-tasks/shared-functions
 
 function check_fast_fails() {
   set +x
-
   if [ "${create_lbs}" != "true" ]; then
     if [ "${BBL_IAAS}" != "gcp" ]; then
       echo "\$IS_BOSH_LITE requires \$BBL_IAAS to be set to 'gcp'"
       exit 1
     fi
   else
-    if [ -z "${LB_DOMAIN}" ]; then
-      echo "\$LB_DOMAIN is a required parameter.  Please set the domain."
+    if [ "${BBL_LB_TYPE}" != "cf" ] && [ "${BBL_LB_TYPE}" != "concourse" ]; then
+      echo "\$BBL_LB_TYPE must be one of [cf, concourse]."
+      exit 1
+    fi
+
+    if [ -z "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "cf" ]; then
+      echo "\$LB_DOMAIN is a required parameter when \$BBL_LB_TYPE=cf.  Please set the domain."
+      exit 1
+    fi
+
+    if [ -n "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "concourse" ]; then
+      echo "\$LB_DOMAIN should not be set when \$BBL_LB_TYPE=concourse."
       exit 1
     fi
 
@@ -112,7 +121,14 @@ function main() {
       local bbl_cert_key
       write_bbl_certs
 
-      lb_flags="--lb-type=cf --lb-cert=${bbl_cert_path} ${bbl_cert_chain_flag} --lb-key=${bbl_key_path} --lb-domain=${LB_DOMAIN}"
+      lb_flags="--lb-type=${BBL_LB_TYPE} --lb-cert=${bbl_cert_path} ${bbl_cert_chain_flag} --lb-key=${bbl_key_path} --lb-domain=${LB_DOMAIN}"
+    fi
+
+    local domain_flag
+    domain_flag=""
+
+    if [ -n "${LB_DOMAIN}" -a ! -f bbl-state.json ]; then
+      domain_flag="--domain=${LB_DOMAIN}"
     fi
 
     bbl plan \
@@ -127,7 +143,6 @@ function main() {
 
     bbl --debug up \
       ${name_flag} \
-      ${lb_flags} \
       ${ops_arguments} \
       ${BBL_EXTRA_FLAGS} > "${root_dir}/bbl_up.txt"
   popd
